/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as TemplatesVesperRouteImport } from './routes/templates.vesper'
import { Route as TemplatesVellumRouteImport } from './routes/templates.vellum'
import { Route as TemplatesSereinRouteImport } from './routes/templates.serein'
import { Route as TemplatesAuraRouteImport } from './routes/templates.aura'
import { Route as ComponentsIdRouteImport } from './routes/components.$id'
import { Route as BlocksCategoryRouteImport } from './routes/blocks.$category'
import { Route as BlocksCategoryBlockRouteImport } from './routes/blocks.$category.$block'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesVesperRoute = TemplatesVesperRouteImport.update({
  id: '/templates/vesper',
  path: '/templates/vesper',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesVellumRoute = TemplatesVellumRouteImport.update({
  id: '/templates/vellum',
  path: '/templates/vellum',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSereinRoute = TemplatesSereinRouteImport.update({
  id: '/templates/serein',
  path: '/templates/serein',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesAuraRoute = TemplatesAuraRouteImport.update({
  id: '/templates/aura',
  path: '/templates/aura',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIdRoute = ComponentsIdRouteImport.update({
  id: '/components/$id',
  path: '/components/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksCategoryRoute = BlocksCategoryRouteImport.update({
  id: '/blocks/$category',
  path: '/blocks/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksCategoryBlockRoute = BlocksCategoryBlockRouteImport.update({
  id: '/$block',
  path: '/$block',
  getParentRoute: () => BlocksCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks/$category': typeof BlocksCategoryRouteWithChildren
  '/components/$id': typeof ComponentsIdRoute
  '/templates/aura': typeof TemplatesAuraRoute
  '/templates/serein': typeof TemplatesSereinRoute
  '/templates/vellum': typeof TemplatesVellumRoute
  '/templates/vesper': typeof TemplatesVesperRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/blocks/$category/$block': typeof BlocksCategoryBlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks/$category': typeof BlocksCategoryRouteWithChildren
  '/components/$id': typeof ComponentsIdRoute
  '/templates/aura': typeof TemplatesAuraRoute
  '/templates/serein': typeof TemplatesSereinRoute
  '/templates/vellum': typeof TemplatesVellumRoute
  '/templates/vesper': typeof TemplatesVesperRoute
  '/blocks': typeof BlocksIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/blocks/$category/$block': typeof BlocksCategoryBlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks/$category': typeof BlocksCategoryRouteWithChildren
  '/components/$id': typeof ComponentsIdRoute
  '/templates/aura': typeof TemplatesAuraRoute
  '/templates/serein': typeof TemplatesSereinRoute
  '/templates/vellum': typeof TemplatesVellumRoute
  '/templates/vesper': typeof TemplatesVesperRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/blocks/$category/$block': typeof BlocksCategoryBlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks/$category'
    | '/components/$id'
    | '/templates/aura'
    | '/templates/serein'
    | '/templates/vellum'
    | '/templates/vesper'
    | '/blocks/'
    | '/components/'
    | '/blocks/$category/$block'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks/$category'
    | '/components/$id'
    | '/templates/aura'
    | '/templates/serein'
    | '/templates/vellum'
    | '/templates/vesper'
    | '/blocks'
    | '/components'
    | '/blocks/$category/$block'
  id:
    | '__root__'
    | '/'
    | '/blocks/$category'
    | '/components/$id'
    | '/templates/aura'
    | '/templates/serein'
    | '/templates/vellum'
    | '/templates/vesper'
    | '/blocks/'
    | '/components/'
    | '/blocks/$category/$block'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksCategoryRoute: typeof BlocksCategoryRouteWithChildren
  ComponentsIdRoute: typeof ComponentsIdRoute
  TemplatesAuraRoute: typeof TemplatesAuraRoute
  TemplatesSereinRoute: typeof TemplatesSereinRoute
  TemplatesVellumRoute: typeof TemplatesVellumRoute
  TemplatesVesperRoute: typeof TemplatesVesperRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/vesper': {
      id: '/templates/vesper'
      path: '/templates/vesper'
      fullPath: '/templates/vesper'
      preLoaderRoute: typeof TemplatesVesperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/vellum': {
      id: '/templates/vellum'
      path: '/templates/vellum'
      fullPath: '/templates/vellum'
      preLoaderRoute: typeof TemplatesVellumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/serein': {
      id: '/templates/serein'
      path: '/templates/serein'
      fullPath: '/templates/serein'
      preLoaderRoute: typeof TemplatesSereinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/aura': {
      id: '/templates/aura'
      path: '/templates/aura'
      fullPath: '/templates/aura'
      preLoaderRoute: typeof TemplatesAuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$id': {
      id: '/components/$id'
      path: '/components/$id'
      fullPath: '/components/$id'
      preLoaderRoute: typeof ComponentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$category': {
      id: '/blocks/$category'
      path: '/blocks/$category'
      fullPath: '/blocks/$category'
      preLoaderRoute: typeof BlocksCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$category/$block': {
      id: '/blocks/$category/$block'
      path: '/$block'
      fullPath: '/blocks/$category/$block'
      preLoaderRoute: typeof BlocksCategoryBlockRouteImport
      parentRoute: typeof BlocksCategoryRoute
    }
  }
}

interface BlocksCategoryRouteChildren {
  BlocksCategoryBlockRoute: typeof BlocksCategoryBlockRoute
}

const BlocksCategoryRouteChildren: BlocksCategoryRouteChildren = {
  BlocksCategoryBlockRoute: BlocksCategoryBlockRoute,
}

const BlocksCategoryRouteWithChildren = BlocksCategoryRoute._addFileChildren(
  BlocksCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksCategoryRoute: BlocksCategoryRouteWithChildren,
  ComponentsIdRoute: ComponentsIdRoute,
  TemplatesAuraRoute: TemplatesAuraRoute,
  TemplatesSereinRoute: TemplatesSereinRoute,
  TemplatesVellumRoute: TemplatesVellumRoute,
  TemplatesVesperRoute: TemplatesVesperRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
